### ISSUE TITLE
Invalid .pullapprove.yml

### ISSUE THREAD

**Issue by juwara0** [ciena-frost/ember-frost-file-picker#43]
I am seeing a message in the section where we have the continuous integration, bit hound and pull approve in pull requests stating that something is wrong with the .pullapprove.yml:

```
Invalid .pullapprove.yml, check pullapprove.com for details
```

**Comment by juwara0** [comment]
Here is the PR that I saw this message show up: https://github.com/ciena-frost/ember-frost-file-picker/pull/42

**Comment by sglanzer** [comment]
In those cases the memebership list from github doesn't match pullapprove, so it just needs to be synced https://pullapprove.com/ciena-frost/ember-frost-file-picker/settings/ "Sync with github" (I've gone ahead and done it in this case)
