### ISSUE TITLE
Update ember-try matrix in travis.yml

### ISSUE THREAD

**Issue by juwara0** [ciena-frost/ember-frost-file-picker#44]
What should the ember-try matrix in `travis.yml` be for this repo?

https://github.com/ciena-frost/ember-frost-file-picker/blob/ee19c18ce07749143de9f036c31b4e6e771bf719/.travis.yml#L24-L25

**Comment by sglanzer** [comment]
At a minimum
 - EMBER_TRY_SCENARIO=ember-2-8
 - EMBER_TRY_SCENARIO=default
 - EMBER_TRY_SCENARIO=ember-release

**Comment by rox163** [comment]
resolved via https://github.com/ciena-frost/ember-frost-file-picker/pull/50
